apiVersion: v1
kind: Secret

metadata:
  name: user-secret

type: Opaque

stringData:

  SPRING_DATASOURCE_USERNAME: root

  SPRING_DATASOURCE_PASSWORD: root

  JWT_SECRET: ChangeThisToYourVeryStrongJWTSecret